# Generated by Django 5.1.1 on 2024-09-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('studio', models.CharField(max_length=30)),
                ('score', models.IntegerField(max_length=10)),
            ],
        ),
    ]
